### ISSUE TITLE
 ! LaTeX Error: File `img/*.eps' not found.

### ISSUE THREAD

**Issue by git-hub-tig** [liuxinyu95/unplugged#8] opened 2018-11-27 19:53 UTC
Hi master!.
I have texlive 2018 in my centos7.
I got the fonts(simsun simhei consolas ) ready for your wonderful book, but i still found  the repo may loss many *.eps files in "img" dir.
like Babylonian_numerals.eps  clay-envelope.eps.
I will pay attention to your progress!
Great Job!

**Comment by liuxinyu95** [comment] 2018-12-02 09:49
Thanks a lot for let me know this. I just fixed the build issue and verified it with a clean git cloning in Mac OS X.

The issue was caused by my previous attempt to improve the build performance. The main tex file manages the chapters with `\subimport`. However, I need also make sure the dependent images (eps files) are generated before running the xelatex. The latest fixing use Makefile to recursively build the `image` target for each chapters.

Please pull the latest version and try to see if there are any other issues. 

Thanks.
--
Xinyu

**Comment by liuxinyu95** [comment] 2019-01-17 22:11
Closed as no one raise this issue again.

**Closed by liuxinyu95** 2019-01-17 22:11 UTC
Labels: bug
